Repository carlkid1499/My-Health-Patient-Portal-Project, pull requests merged in 2020-12, with the labels that each got.

#49 Code fixes for Live webpage
  index.php
  logout.php
  php/healthcare_worker_portal.php
  php/insurance_plans.php
  php/patient_portal.php
  php/pharmacy.php
  php/queries.php
  php/welcome.php
Labels: bug fix, enhancement

#50 page auto refreshes upon pressing submit to update info.
  php/healthcare_worker_portal.php
  php/patient_portal.php
Labels: enhancement

#51 Pharmacy search fix
  php/pharmacy_portal.php
  php/queries.php
Labels: bug fix

#52 Doctor add note
  php/healthcare_worker_portal.php
  php/queries.php
  python-scripts/generator.py
Labels: enhancement

#54 modified create user form
  php/healthcare_worker_portal.php
  php/patient_portal.php
  php/pharmacy_portal.php
  php/welcome.php
Labels: enhancement
